# Code Generated by Sidekick is for learning and experimentation purposes only.
import streamlit as st

st.set_page_config(page_title="Compliance Dashboard", page_icon=":guardsman:", layout="wide")
st.title("Compliance Officer Dashboard")
st.markdown("""
Welcome to your multi-app compliance management suite. Use the sidebar to navigate between modules:
- Regulatory Feed
- Policy Tracker
- Task Manager
- Analytics
- Admin Tools
""")
