# Code Generated by Sidekick is for learning and experimentation purposes only.
import streamlit as st

st.title("Home: Compliance Dashboard Overview")

# Navigation mapping — page_number: (Button label, target)
navigation_targets = [
    ("Go to Regulatory Feed", "2_Regulatory_Feed"),
    ("Go to Policy Tracker", "3_Policy_Tracker"),
    ("Go to Task Manager", "4_Task_Manager"),
    ("Go to Analytics", "5_Analytics"),
    ("Go to Admin Tools", "6_Admin_Tools")
]

# Show content summary
st.markdown("""
#### Key Features:
- Regulatory updates summarized with AI
- Track affected policies and review status
- Assign and monitor compliance tasks
- View analytics and trends
""")

if "regulations" in st.session_state:
    st.write(f"Registered regulations: {len(st.session_state['regulations'])}")
if "policies" in st.session_state:
    st.write(f"Registered policies: {len(st.session_state['policies'])}")
if "tasks" in st.session_state:
    st.write(f"Open tasks: {len([t for t in st.session_state['tasks'] if t['status'] != 'Complete'])}")

# Navigation buttons
st.header("Quick Navigation")

for label, page in navigation_targets:
    if st.button(label):
        st.experimental_set_query_params(page=page)
        st.success(f"Navigating to {label}...")
        st.experimental_rerun()

st.info("Or use the sidebar navigation menu at any time.")
