# Code Generated by Sidekick is for learning and experimentation purposes only.
import streamlit as st

st.title("Home: Compliance Dashboard Overview")

st.markdown("""
#### Key Features:
- Regulatory updates summarized with AI
- Track affected policies and review status
- Assign and monitor compliance tasks
- View analytics and trends
""")

if "regulations" in st.session_state:
    st.write(f"Registered regulations: {len(st.session_state['regulations'])}")
if "policies" in st.session_state:
    st.write(f"Registered policies: {len(st.session_state['policies'])}")
if "tasks" in st.session_state:
    st.write(f"Open tasks: {len([t for t in st.session_state['tasks'] if t['status'] != 'Complete'])}")
