# Code Generated by Sidekick is for learning and experimentation purposes only.
import streamlit as st
from utils.summarization import summarize_with_claude

st.title("Regulatory Feed")

if "regulations" not in st.session_state:
    st.session_state["regulations"] = []

regulator_filter = st.sidebar.selectbox("Filter by Regulator", ["All"] + list({r['regulator'] for r in st.session_state["regulations"]}))
impact_filter = st.sidebar.selectbox("Impact Level", ["All", "High", "Medium", "Low"])

def filter_regulations(data, regulator, impact):
    filtered = data
    if regulator != "All":
        filtered = [r for r in filtered if r["regulator"] == regulator]
    if impact != "All":
        filtered = [r for r in filtered if r["impact"] == impact]
    return filtered

filtered_regs = filter_regulations(st.session_state["regulations"], regulator_filter, impact_filter)

for idx, reg in enumerate(filtered_regs):
    st.subheader(reg["title"])
    st.write(f"**Date:** {reg['date']} | **Regulator:** {reg['regulator']} | **Impact:** {reg['impact']} | **Status:** {reg['status']}")
    with st.expander("Details & AI Summary"):
        st.write(reg["body"])
        if st.button(f"Summarize with Claude ({reg['title']})", key=f"summ_{idx}"):
            with st.spinner("Summarizing..."):
                summary = summarize_with_claude(reg["body"], st.secrets["ANTHROPIC_API_KEY"])
                st.success(summary)
    st.markdown("---")
