# Code Generated by Sidekick is for learning and experimentation purposes only.
import streamlit as st
from utils.summarization import summarize_with_claude
# Assume you fetch or load regulations from db.py

st.title("Regulatory Feed")
regulations = st.session_state.get("regulations", [])

if not regulations:
    st.info("No regulations yet. Add some on Admin page.")

for idx, reg in enumerate(regulations):
    st.subheader(reg["title"])
    st.write(f"**Date:** {reg['date']}  |  **Regulator:** {reg['regulator']}  |  **Impact:** {reg['impact']}  |  **Status:** {reg['status']}")
    with st.expander("Details & AI Summary"):
        st.write(reg["body"])
        if st.button(f"Summarize with Claude", key=f"summ_{idx}"):
            with st.spinner("Summarizing..."):
                summary = summarize_with_claude(reg["body"], st.secrets["ANTHROPIC_API_KEY"])
                st.success(summary)
