# Code Generated by Sidekick is for learning and experimentation purposes only.
import streamlit as st
from utils import db
from utils.summarization import summarize_with_claude

db.initialize_db()

st.title("Regulatory Feed")

regulations = db.get_all_regulations()
regulator_filter = st.sidebar.selectbox(
    "Filter by Regulator", ["All"] + sorted({r['regulator'] for r in regulations})
)
impact_filter = st.sidebar.selectbox("Impact Level", ["All", "High", "Medium", "Low"])

def filter_regs(data, regulator, impact):
    if regulator != "All":
        data = [r for r in data if r["regulator"] == regulator]
    if impact != "All":
        data = [r for r in data if r["impact"] == impact]
    return data

filtered_regs = filter_regs(regulations, regulator_filter, impact_filter)

if not filtered_regs:
    st.info("No regulations found. Add via Admin Tools.")
for idx, reg in enumerate(filtered_regs):
    st.subheader(reg["title"])
    st.write(f"**Date:** {reg['date']} | **Regulator:** {reg['regulator']} | **Impact:** {reg['impact']} | **Status:** {reg['status']}")
    with st.expander("Details & AI Summary"):
        st.write(reg["body"])
        if st.button(f"Summarize with Claude ({reg['title']})", key=f"summ_{reg['id']}"):
            with st.spinner("Summarizing..."):
                summary = summarize_with_claude(reg["body"], st.secrets["ANTHROPIC_API_KEY"])
                st.success(summary)
    st.markdown("---")
