# Code Generated by Sidekick is for learning and experimentation purposes only.
import streamlit as st
from utils import db

db.initialize_db()

st.title("Policy Tracker")
st.header("Add New Policy")

with st.form("policy_form"):
    name = st.text_input("Policy Name")
    description = st.text_area("Description")
    impacted_by = st.text_input("Impacted by Regulation")
    review_status = st.selectbox("Status", ["Pending Review", "In Review", "Approved"])
    submit = st.form_submit_button("Add Policy")
    if submit and name:
        db.insert_policy({
            "name": name,
            "description": description,
            "impacted_by": impacted_by,
            "review_status": review_status
        })
        st.success("Policy added!")

policies = db.get_all_policies()
st.header("Registered Policies")
if not policies:
    st.info("No policies yet. Add one above.")
for pol in policies:
    st.subheader(pol["name"])
    st.write(f"**Description:** {pol['description']}")
    st.write(f"**Impacted by:** {pol['impacted_by']}")
    st.write(f"**Status:** {pol['review_status']}")
    st.markdown("---")
