# Code Generated by Sidekick is for learning and experimentation purposes only.
import streamlit as st

st.title("Policy Tracker")

if "policies" not in st.session_state:
    st.session_state["policies"] = []

st.header("Add New Policy")
with st.form("policy_form"):
    name = st.text_input("Policy Name")
    description = st.text_area("Description")
    impacted_by = st.text_input("Impacted by Regulation")
    review_status = st.selectbox("Status", ["Pending Review", "In Review", "Approved"])
    submit = st.form_submit_button("Add Policy")
    if submit and name:
        st.session_state["policies"].append({
            "name": name,
            "description": description,
            "impacted_by": impacted_by,
            "review_status": review_status
        })
        st.success("Policy added!")

st.header("Registered Policies")
for idx, pol in enumerate(st.session_state["policies"]):
    st.subheader(pol["name"])
    st.write(f"**Description:** {pol['description']}")
    st.write(f"**Impacted by:** {pol['impacted_by']}")
    st.write(f"**Status:** {pol['review_status']}")
    st.markdown("---")
