# Code Generated by Sidekick is for learning and experimentation purposes only.
import streamlit as st
from utils import db

db.initialize_db()

st.title("Task Manager")

policies = db.get_all_policies()

st.header("Assign New Task")
with st.form("assign_task_form"):
    task = st.text_area("Task Description")
    related_policy = st.selectbox("Related Policy", [p["name"] for p in policies] + ["None"])
    assigned_to = st.text_input("Assigned To")
    status = st.selectbox("Status", ["Open", "In Progress", "Complete"])
    submit = st.form_submit_button("Assign Task")
    if submit and task:
        db.insert_task({
            "task": task,
            "policy": related_policy,
            "assigned_to": assigned_to,
            "status": status
        })
        st.success("Task assigned!")

tasks = db.get_all_tasks()
st.header("Open Tasks")
if not tasks:
    st.info("No tasks to show. Assign one above.")
for t in tasks:
    st.subheader(t["task"])
    st.write(f"**Policy:** {t['policy']}")
    st.write(f"**Assigned to:** {t['assigned_to']}")
    st.write(f"**Status:** {t['status']}")
    st.markdown("---")
