# Code Generated by Sidekick is for learning and experimentation purposes only.
import streamlit as st

st.title("Task Manager")

if "tasks" not in st.session_state:
    st.session_state["tasks"] = []

st.header("Assign New Task")
with st.form("assign_task_form"):
    task = st.text_area("Task Description")
    related_policy = st.selectbox("Related Policy", [p["name"] for p in st.session_state.get("policies", [])] + ["None"])
    assigned_to = st.text_input("Assigned To")
    status = st.selectbox("Status", ["Open", "In Progress", "Complete"])
    submit = st.form_submit_button("Assign Task")
    if submit and task:
        st.session_state["tasks"].append({
            "task": task,
            "policy": related_policy,
            "assigned_to": assigned_to,
            "status": status
        })
        st.success("Task assigned!")

st.header("Open Tasks")
for idx, t in enumerate(st.session_state["tasks"]):
    st.subheader(t["task"])
    st.write(f"**Policy:** {t['policy']}")
    st.write(f"**Assigned to:** {t['assigned_to']}")
    st.write(f"**Status:** {t['status']}")
    st.markdown("---")
