# Code Generated by Sidekick is for learning and experimentation purposes only.
import streamlit as st
import pandas as pd
from utils import db

db.initialize_db()

st.title("Analytics")

regs = db.get_all_regulations()
policies = db.get_all_policies()
tasks = db.get_all_tasks()

st.subheader("Regulation Counts by Impact")
if regs:
    df = pd.DataFrame(regs)
    st.bar_chart(df['impact'].value_counts())
else:
    st.info("No regulations data available.")

st.subheader("Policy Review Status")
if policies:
    dfp = pd.DataFrame(policies)
    st.bar_chart(dfp['review_status'].value_counts())
else:
    st.info("No policy data available.")

st.subheader("Tasks by Status")
if tasks:
    dft = pd.DataFrame(tasks)
    st.bar_chart(dft['status'].value_counts())
else:
    st.info("No task data available.")
