# Code Generated by Sidekick is for learning and experimentation purposes only.
import streamlit as st
import pandas as pd

st.title("Analytics")

regs = st.session_state.get("regulations", [])
policies = st.session_state.get("policies", [])
tasks = st.session_state.get("tasks", [])

st.subheader("Regulation Counts by Impact")
if regs:
    df = pd.DataFrame(regs)
    st.bar_chart(df['impact'].value_counts())

st.subheader("Policy Review Status")
if policies:
    dfp = pd.DataFrame(policies)
    st.bar_chart(dfp['review_status'].value_counts())

st.subheader("Tasks by Status")
if tasks:
    dft = pd.DataFrame(tasks)
    st.bar_chart(dft['status'].value_counts())
