# Code Generated by Sidekick is for learning and experimentation purposes only.
import streamlit as st
from utils import db
import datetime

db.initialize_db()

st.title("Admin Tools")

st.header("Manually Add Regulatory Update")
with st.form("regulation_form"):
    title = st.text_input("Title")
    date = st.date_input("Date", value=datetime.date.today())
    regulator = st.selectbox("Regulator", ["SEC", "ESMA", "FINRA", "Other"])
    impact = st.selectbox("Impact Level", ["High", "Medium", "Low"])
    body = st.text_area("Regulatory Details")
    status = st.selectbox("Status", ["Action Required", "Open", "Informational"])
    submit = st.form_submit_button("Add Regulation")
    if submit and title and body:
        new_reg = {
            "title": title,
            "date": date.strftime('%Y-%m-%d'),
            "regulator": regulator,
            "impact": impact,
            "body": body,
            "status": status
        }
        db.insert_regulation(new_reg)
        st.success("Regulation added!")

st.header("Clear All Data")
if st.button("Clear All Data"):
    db.clear_all()
    st.success("All persistent data cleared.")
